version : "3.8"

services:
  fapi :
    image : "python:3.11-alpine"
    ports :
      - "50000:8000"
    volumes :
      - $PWD:/code
    tty : true
  db:
    image: postgres
    restart: always
    ports :
      - "8080:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - "$PWD/redis:/code"
    tty : true